# Generated by Django 4.2.4 on 2023-10-03 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sampleapp', '0002_detail_delete_employee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detail',
            name='phone',
            field=models.PositiveIntegerField(),
        ),
    ]
