# Generated by Django 4.2.4 on 2023-10-03 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sampleapp', '0003_alter_detail_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detail',
            name='phone',
            field=models.IntegerField(max_length=12),
        ),
    ]
